spring:
    application:
        name: kc-os
    data:
        mongodb:
            uri: mongodb://localhost:27017/connection
            database: keycloak
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri:  http://localhost:9090/realms/OpenSource
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
    auth:
        converter:
            resource-id: open-rest-api
